"""Emit the SPA validation contract (singleton source of truth) as JSON."""

import json

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from kyc.models import Document, KYCApplication
from kyc.serializers.fields import DEFAULT_PHONE_REGION, DOB_MIN, PasswordField
from kyc.services.otp import OTP_LENGTH

APPLICATION_LENGTH_FIELDS = (
    "full_name",
    "nationality",
    "phone",
    "address_line1",
    "address_line2",
    "city",
    "state",
    "postal_code",
    "country",
    "id_number",
)


class Command(BaseCommand):
    help = "Print the SPA validation contract as JSON (committed to frontend/src/lib/)."

    def handle(self, *args, **options):
        user_model = get_user_model()
        application_lengths = {
            field: KYCApplication._meta.get_field(field).max_length
            for field in APPLICATION_LENGTH_FIELDS
        }
        contract = {
            "_comment": "Generated by `python manage.py validation_contract`. Do not edit by hand.",
            "dob_min": DOB_MIN.isoformat(),
            "max_upload_mb": settings.MAX_UPLOAD_SIZE_MB,
            "allowed_upload_extensions": settings.ALLOWED_UPLOAD_EXTENSIONS,
            "max_documents_per_application": settings.MAX_DOCUMENTS_PER_APPLICATION,
            "phone_default_region": DEFAULT_PHONE_REGION,
            "phone_max_length": application_lengths["phone"],
            "password_min_length": PasswordField().min_length,
            "otp_length": OTP_LENGTH,
            "name_max_length": user_model._meta.get_field("first_name").max_length,
            "email_max_length": user_model._meta.get_field("email").max_length,
            "page_size": settings.REST_FRAMEWORK["PAGE_SIZE"],
            "application_max_lengths": application_lengths,
            "gender_values": list(user_model.Gender.values),
            "application_id_types": list(KYCApplication.IDType.values),
            "document_doc_types": list(Document.DocType.values),
            "application_statuses": list(KYCApplication.Status.values),
        }
        self.stdout.write(json.dumps(contract, indent=2))
