# Generated by Django 6.0.8 on 2026-08-17 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    """Mark all pre-existing users as email-verified.

    Hard verification only applies to accounts created after this field
    shipped; locking out every existing user (including reviewers/admins)
    would be a self-inflicted outage.
    """
    User = apps.get_model("kyc", "User")
    User.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_user_gender_user_middle_name_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing_users, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose'], name='kyc_emailot_user_id_fb9628_idx')],
            },
        ),
    ]
