# Generated by Django 6.0.8 on 2026-08-17 06:32

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_user_optional_profile_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', kyc.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
